all:
	@make copy -C kill_software_update
	@make copy -C fstab
	@make copy -C n1ghtshade_app
	@make copy -C non_default_apps
	@make copy -C jb_init
	@make -C hacktivate

clean:
	@make clean -C kill_software_update
	@make clean -C fstab
	@make clean -C n1ghtshade_app
	@make clean -C non_default_apps
	@make clean -C jb_init
	@make clean -C hacktivate
